# -*- coding: utf-8 -*-
"""webscraping1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lZ-6ewbEbuauuMD8xGQ0T3iZifaBdJqf
"""

from bs4 import BeautifulSoup
import requests
import pandas as pd

url = 'https://www.basketball-reference.com/leagues/NBA_2020_totals.html'
req = requests.get(url)
print(req)

soup = BeautifulSoup(req.content, 'html.parser')

tablea = soup.find(name='table')

df = pd.read_html(str(tablea))[0].set_index('Rk')

df.head()

df.to_csv('scraping_basketball.csv')